accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from accounts.views import LoginView

app_name = 'accounts'

urlpatterns = [
    path(
        'login/', 
        LoginView.as_view(),
        name='login'
    ),
    path(
        'logout/',
        LogoutView.as_view(),
        name='logout'
    ),
]

app/urls.py
from django.urls import path
from django.views.generic import TemplateView
from app.views import *

app_name = 'app'

urlpatterns = [
    path(
        'department/<int:pk_department>/course/<int:pk_course>/',
        TemplateView.as_view(template_name='app/course_study-list.html'),
        name='course_study_list'),
    path(
        'student/form/',
        StudentCreateView.as_view(),
        name='student-add'
    ),
    path(
        'student/<str:uid>/detail/',
        StudentDetailView.as_view(),
        name='student-detail'
    ),
    path(
        'student/<str:uid>/document/add/',
        DocumentCreateView.as_view(),
        name='document-create'
    ),
    path(
        'student/<str:uid>/admisssion/form/',
        AdmissionFileCreateView.as_view(),
        name='admission-form'
    ),
    path(
        'student/search/',
        StudentSearchListView.as_view(),
        name='search'),
    path(
        'proces/',
        VerbalProcesCreateView.as_view(),
        name='proces'
    ),
    path('department/<int:pk>/students/',
         CourseStudyDetail.as_view(), name='course-detail'),

]

archives/urls.py
from django.views.generic import TemplateView
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from archives.views import HomeTemplateView

admin.site.site_header = "SGCA-FS Admin"
admin.site.site_title = "SGCA-FS Portail"
admin.site.index_title = "Bienvenue sur SGCA-FS"

urlpatterns = [
    path('', HomeTemplateView.as_view(), name='home'),
    path('app/', include('app.urls', namespace='app')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base/navbar.html
<header class="navbar navbar-header navbar-header-fixed">
    <!-- <a href="#" id="sidebarMenuOpen" class="burger-menu"><i data-feather="arrow-left"></i></a>
    <div class="navbar-brand">
      <a href="../index.html" class="df-logo">dash<span>forge</span></a>
    </div> -->
    <div id="navbarMenu" class="navbar-menu-wrapper">
      
      <ul class="nav navbar-menu">
        
        <li class="nav-item with-sub">
          <a href="#" class="nav-link"><i data-feather="layers"></i> Departements</a>
          <div class="navbar-menu-sub">
            <div class="d-lg-flex">
             {% for department in departments %}
             <ul>
              <li class="nav-label">{{department.name}}</li>              
              {% for course in department.course_of_studies.all %}
              <li class="nav-sub-item"><a href="{{course.get_absolute_url}}" class="nav-sub-link">{{course.name}}</a></li>
                
              {% endfor %}
            </ul>
             {% endfor %}
              
            </div>
          </div>
        
        </li>
        
        <ul class="nav ml-auto">
          <li class="nav-item">
            <form class="form-inline" method="GET" action="{% url 'app:search' %}">
  
              <div class="form-group mx-sm-3 mb-2">
                <label for="search" class="sr-only">Search</label>
                <input type="text" name="serial_number" class="form-control-sm" id="search" placeholder="Entrez le matricule">
              </div>
              <button type="submit" class="btn btn-primary btn-sm mb-2">Rechercher</button>
            </form>
          </li>
          <li class="nav-item">
            {% if not request.user.is_authenticated %}
            <a href="{% url 'accounts:login' %}" class="btn btn-primary btn-sm">Se connecter</a>
              {% else %}
            <a href="{% url 'accounts:logout' %}" class="btn btn-danger btn-sm">Se deconnecter </a>
  
            {% endif %}
          </li>
        </ul>
        </ul>
    </div>
    <!-- <div class="navbar-right">
      <a href="http://dribbble.com/themepixels" class="btn btn-social"><i class="fab fa-dribbble"></i></a>
      <a href="https://github.com/themepixels" class="btn btn-social"><i class="fab fa-github"></i></a>
      <a href="https://twitter.com/themepixels" class="btn btn-social"><i class="fab fa-twitter"></i></a>
      <a href="https://themeforest.net/item/dashforge-responsive-admin-dashboard-template/23725961" class="btn btn-buy"><i data-feather="shopping-bag"></i> <span>Buy Now</span></a>
    </div> -->
  </header>