app/urls.py
from django.urls import path
from django.views.generic import TemplateView
from app.views import *

app_name = 'app'

urlpatterns = [
    path(
        'department/<int:pk_department>/course/<int:pk_course>/',
        TemplateView.as_view(template_name='app/course_study-list.html'),
        name='course_study_list'),
    path(
        'student/form/',
        StudentCreateView.as_view(),
        name='student-add'
    ),
    path(
        'student/<str:uid>/detail/',
        StudentDetailView.as_view(),
        name='student-detail'
    ),
    path(
        'student/<str:uid>/document/add/',
        DocumentCreateView.as_view(),
        name='document-create'
    ),
    path(
        'student/<str:uid>/admisssion/form/',
        AdmissionFileCreateView.as_view(),
        name='admission-form'
    ),
    path(
        'student/search/',
        StudentSearchListView.as_view(),
        name='search'),
    path(
        'proces/',
        VerbalProcesCreateView.as_view(),
        name='proces'
    ),
    path('department/<int:pk>/students/',
         CourseStudyDetail.as_view(), name='course-detail'),

]

archives/urls.py
from django.views.generic import TemplateView
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from archives.views import HomeTemplateView

admin.site.site_header = "SGCA-FS Admin"
admin.site.site_title = "SGCA-FS Portail"
admin.site.index_title = "Bienvenue sur SGCA-FS"

urlpatterns = [
    path('', HomeTemplateView.as_view(), name='home'),
    path('app/', include('app.urls', namespace='app')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>

    {% block title %}

    {% endblock title %} - FS | UNIV-NDERE

  </title>
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans&family=Roboto:wght@500&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'lib/fortawesome/css/all.min.css' %}">

  {% block extrastyle %}
    
  {% endblock extrastyle %}

  <link rel="stylesheet" href="{% static 'css/dashforge.filemgr.css' %}">
  <link rel="stylesheet" href="{% static 'css/dashforge.css' %}">
  <link rel="stylesheet" href="{% static 'css/dashforge.demo.css' %}">
  <!-- <link rel="stylesheet" href="{% static 'css/app.css' %}"> -->


</head>

<body class="app-filemgr">

  {% include "base/navbar.html" %}
  <div class="content content-components">
    <div class="container">
      <!-- <div class="row">
        <div class="col-12" style="width: 100%;">
        
        </div>
      </div> -->
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb breadcrumb-style1 mg-b-0">
          {% block breadcrumbs %}


          <li class="breadcrumb-item {% if request.path == '/' %}
                      active
                      {% endif %}"><a href="/">Accueil</a></li>

          {% endblock breadcrumbs %}
        </ol>
      </nav>
      {% block content %}

      {% endblock content %}



      <!-- <footer class="content-footer">
            <div>
              <span>&copy; 2019 DashForge v1.0.0. </span>
              <span>Made by <a href="http://themepixels.me/">ThemePixels</a></span>
            </div>
            <div>
              <nav class="nav">
                <a href="https://themeforest.net/licenses/standard" class="nav-link">Licenses</a>
                <a href="../change-log.html" class="nav-link">Change Log</a>
                <a href="https://discordapp.com/invite/RYqkVuw" class="nav-link">Get Help</a>
              </nav>
            </div>
          </footer>
       -->
    </div>
  </div>

  <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
  <!-- <script src="{% static 'js/popper.min.js' %}"></script> -->
  <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'lib/feather-icons/feather.min.js' %}"></script>
  <script src="{% static 'js/perfect-scrollbar.min.js' %}"></script>

  <script src="{% static 'js/dashforge.filemgr.js' %}"></script>
  <script src="{% static 'js/dashforge.js' %}"></script>


  {% block script %}

  {% endblock script %}
  <script>
    $(document).ready(function(){
  {% block javascript %}

  {% endblock javascript %}
  });
  </script>
</body>

</html>

templates/base_site.html
{% extends "base.html" %}



{% block content %}
<div class="filemgr-wrapper">
  <div class="filemgr-sidebar">
    <div class="filemgr-sidebar-header">
      
      <div class="dropdown dropdown-icon flex-fill mg-l-10">
        <button class="btn btn-xs btn-block btn-primary" data-toggle="dropdown">Ajouter <i
            data-feather="chevron-down"></i></button>
        <div class="dropdown-menu tx-13">
          <a href="#" class="dropdown-item"><i data-feather="file"></i><span>Nouvel étudiant</span></a>
          <a href="#" class="dropdown-item"><i data-feather="folder"></i><span>Fiche d'admission</span></a>
        </div><!-- dropdown-menu -->
      </div><!-- dropdown -->
    </div><!-- filemgr-sidebar-header -->
    <div class="filemgr-sidebar-body">
      {% for department in departments %}
      <div class="pd-t-20 pd-b-10 pd-x-10">
        <label class="tx-sans tx-uppercase tx-medium tx-10 tx-spacing-1 tx-color-03 pd-l-10">{{department.name}}</label>
        {% if department.has_course_of_studies %}
        <nav class="nav nav-sidebar tx-13">
          {% for course in department.course_of_studies.all %}
          <a href="#" class="nav-link"><i data-feather="folder"></i> <span>{{course.name}}</span></a>

          {% endfor %}
        </nav>
        {% endif %}
      </div>
      {% endfor %}

    </div><!-- filemgr-sidebar-body -->
  </div><!-- filemgr-sidebar -->

  <div class="filemgr-content">
    <div class="filemgr-content-header">
      <i data-feather="search"></i>
      <div class="search-form">
        <input type="search" class="form-control" placeholder="Entrez le matricule">
      </div>
      <nav class="nav d-none d-sm-flex mg-l-auto">
        <a href="#" class="nav-link"><i data-feather="list"></i></a>
        <a href="#" class="nav-link"><i data-feather="alert-circle"></i></a>
        <a href="#" class="nav-link"><i data-feather="settings"></i></a>
      </nav>
    </div>
    <div class="filemgr-content-body">
      <div class="pd-t-20 pd-b-10 pd-x-10">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb breadcrumb-style3 mg-b-0">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
    <li class="breadcrumb-item"><a href="#">Library</a></li>
    <li class="breadcrumb-item active" aria-current="page">Data</li>
          </ol>
        </nav>
        {% block content-body %}

        {% endblock content-body %}
        <!-- filemgr-content-body -->
      </div><!-- filemgr-content -->
    </div>

  </div>
  {% endblock content %}

templates/index.html
{% extends "base.html" %}

{% load humanize %}

{% block title %}
App
{% endblock title %}

{% block content %}
<div class="row">
  <div class="col-12 d-flex ">
    <div class="ml-auto">
      <a class="btn btn-primary btn-sm" href="{% url 'app:student-add' %}">Ajouter un nouvel étudiant</a>
      <a class="btn btn-warning btn-sm ml-3" href="{% url 'app:proces' %}">Ajouter un procès verbal</a>

    </div>
  </div>
</div>
<div class="row">
  <div class="col-12">
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{message.tags}}">
      {{message}}
    </div>
    {% endfor %}
    {% endif %}
  </div>
</div>

<section class="py-4">
  <p class="mb-0">Les étudiants régulièrement inscris</p>
  <hr class="mg-b-40">
  <div class="row tx-14">
    {% for student in recent_students %}
    <div class="col-sm-4 mb-4">
      {% include "app/includes/single-folder.html" with item=student %}
    </div>

    {% empty %}
    <div class="col-12">
      <h5 class="text-center text-primary">Aucun nouvel étudiant</h5>
    </div>
    {% endfor %}

  </div>
</section>

<section class="py-4">
  <p class="mb-0">Tous les procès verbaux</p>
  <hr class="mg-b-40 mt-0">
  <div class="row tx-14">
    {% for proces in verbal_proces %}
    <div class="col-sm-4 mb-4">
      <div class="card card-file">
        <!-- <div class="dropdown-file">
          <a href="#" class="dropdown-link" data-toggle="dropdown"><i data-feather="more-vertical"></i></a>
          <div class="dropdown-menu dropdown-menu-right">
            <a href="#modalViewDetails" data-toggle="modal" class="dropdown-item details"><i data-feather="info"></i>
              Details</a>

            <a href="#" class="dropdown-item delete"><i data-feather="trash"></i>Supprimer</a>
          </div>
        </div> -->
        <div class="card-file-thumb tx-danger">
          <i class="far fa-file"></i>
        </div>
        <div class="card-body">
          <h6 class="text-primary">Procès verbal: {{proces.level.full_name}}</h6>
          <p>année académique: {{proces.academic_year}}</p>
          <!-- <span>Taille du fichier: </span> -->
        </div>
        <div class="card-footer"><span class="d-none d-sm-inline">Date d'ajout: </span><span
            class="text-dark">{{proces.created_at|naturalday}}</span></div>
      </div>
    </div>

    {% empty %}
    <div class="col-12">
      <h5 class="text-center text-primary">Aucun procès verbal enregistré !</h5>
    </div>
    {% endfor %}

  </div>
</section>

<!-- <section class="py-4">
  <h4 class="mb-0">Nouveaux documents</h4>
  <hr class="mg-b-40">
  <div class="row tx-14 px-3">


    {% for document in recent_documents %}
    <div class="col-sm-4 mb-4">
      {% include "app/includes/single-document.html" with item=document %}
    </div>
    {% empty %}
    <div class="col-12">
      <p class="text-center">Aucun nouveau document</p>
    </div>
    {% endfor %}

  </div>
</section> -->
{% endblock content %}