app/urls.py
from django.urls import path
from django.views.generic import TemplateView
from app.views import *

app_name = 'app'

urlpatterns = [
    path(
        'department/<int:pk_department>/course/<int:pk_course>/',
        TemplateView.as_view(template_name='app/course_study-list.html'),
        name='course_study_list'),
    path(
        'student/form/',
        StudentCreateView.as_view(),
        name='student-add'
    ),
    path(
        'student/<str:uid>/detail/',
        StudentDetailView.as_view(),
        name='student-detail'
    ),
    path(
        'student/<str:uid>/document/add/',
        DocumentCreateView.as_view(),
        name='document-create'
    ),
    path(
        'student/<str:uid>/admisssion/form/',
        AdmissionFileCreateView.as_view(),
        name='admission-form'
    ),
    path(
        'student/search/',
        StudentSearchListView.as_view(),
        name='search'),
    path(
        'proces/',
        VerbalProcesCreateView.as_view(),
        name='proces'
    ),
    path('department/<int:pk>/students/',
         CourseStudyDetail.as_view(), name='course-detail'),

]

archives/urls.py
from django.views.generic import TemplateView
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from archives.views import HomeTemplateView

admin.site.site_header = "SGCA-FS Admin"
admin.site.site_title = "SGCA-FS Portail"
admin.site.index_title = "Bienvenue sur SGCA-FS"

urlpatterns = [
    path('', HomeTemplateView.as_view(), name='home'),
    path('app/', include('app.urls', namespace='app')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/templates/app/includes/single-document.html
{% load humanize %}
{% load sizify %}
<div class="card card-file">
  <!-- <div class="dropdown-file">
    <a href="#" class="dropdown-link" data-toggle="dropdown"><i data-feather="more-vertical"></i></a>
    <div class="dropdown-menu dropdown-menu-right">
      <a href="#modalViewDetails" data-toggle="modal" class="dropdown-item details"><i data-feather="info"></i>
        Details</a>

      <a href="#" class="dropdown-item delete"><i data-feather="trash"></i>Supprimer</a>
    </div>
  </div> -->
  <div class="card-file-thumb tx-danger">
    <i class="far fa-file"></i>
  </div>
  <div class="card-body">
    <h6><a href="{{item.file.url}}" class="link-02" target="blank" >{{item.type}} | {{item.semester}}</a></h6>
    <span>Taille du fichier: {{item.file.size|sizify}}</span>
  </div>
  <div class="card-footer"><span class="d-none d-sm-inline">Date d'ajout: </span><span class="text-dark">{{item.created_at|naturalday}}</span></div>
</div>

app/templates/app/includes/single-folder.html
<div class="media media-folder">
  <i data-feather="folder"></i>
  <div class="media-body">
    <h6><a href="{% url 'app:student-detail' uid=item.uid %}" class="link-02"><span
          class="text-primary">{{item.serial_number}}</span>
        {{item.get_full_name}}</a></h6>
    <span>{{item.documents.count}} document{{item.documents.count|pluralize}}</span>
  </div>
  <!-- <div class="dropdown-file">
    <a href="#" class="dropdown-link" data-toggle="dropdown"><i data-feather="more-vertical"></i></a>
    <div class="dropdown-menu dropdown-menu-right">
      <a href="#modalViewDetails" data-toggle="modal" class="dropdown-item details"><i data-feather="info"></i>Détails
      </a>

      <a href="#" class="dropdown-item delete"><i data-feather="trash"></i>Supprimer</a>
    </div>
  </div> -->
</div>