app/urls.py
from django.urls import path
from django.views.generic import TemplateView
from app.views import *

app_name = 'app'

urlpatterns = [
    path(
        'department/<int:pk_department>/course/<int:pk_course>/',
        TemplateView.as_view(template_name='app/course_study-list.html'),
        name='course_study_list'),
    path(
        'student/form/',
        StudentCreateView.as_view(),
        name='student-add'
    ),
    path(
        'student/<str:uid>/detail/',
        StudentDetailView.as_view(),
        name='student-detail'
    ),
    path(
        'student/<str:uid>/document/add/',
        DocumentCreateView.as_view(),
        name='document-create'
    ),
    path(
        'student/<str:uid>/admisssion/form/',
        AdmissionFileCreateView.as_view(),
        name='admission-form'
    ),
    path(
        'student/search/',
        StudentSearchListView.as_view(),
        name='search'),
    path(
        'proces/',
        VerbalProcesCreateView.as_view(),
        name='proces'
    ),
    path('department/<int:pk>/students/',
         CourseStudyDetail.as_view(), name='course-detail'),

]

archives/urls.py
from django.views.generic import TemplateView
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from archives.views import HomeTemplateView

admin.site.site_header = "SGCA-FS Admin"
admin.site.site_title = "SGCA-FS Portail"
admin.site.index_title = "Bienvenue sur SGCA-FS"

urlpatterns = [
    path('', HomeTemplateView.as_view(), name='home'),
    path('app/', include('app.urls', namespace='app')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
import uuid
from django.urls import reverse

from app.managers import StudentManager


class TimeStampModel(models.Model):
    created_at = models.DateField(auto_now=True, auto_now_add=False)
    updated_at = models.DateField(auto_now=False, auto_now_add=True)

    class Meta:
        abstract = True


class CommonModel(TimeStampModel):
    name = models.CharField(max_length=150, verbose_name='Nom')

    def __str__(self):
        return self.name

    class Meta:
        abstract = True


class Level(TimeStampModel):
    full_name = models.CharField(
        max_length=150, verbose_name='Nom', help_text='Exemple: Niveau 1')
    # short_name = models.CharField(max_length=10, verbose_name='Abbréviation')

    def __str__(self):
        return self.full_name

    class Meta:
        verbose_name = 'Niveau'
        verbose_name_plural = 'Niveaux'


class Department(CommonModel):
    class Meta:
        verbose_name = 'Departement'
        verbose_name_plural = 'Departements'

    def has_course_of_studies(self):
        return self.course_of_studies.all()


class CourseOfStudy(CommonModel):
    department = models.ForeignKey(
        Department,
        on_delete=models.CASCADE,
        related_name='course_of_studies'
    )
    # student = models.ManyToManyField(
    #     Student,
    #     blank=True,
    #     related_name='courses_of_studies',
    #     verbose_name='Etudiants'
    # )

    def get_absolute_url(self):
        return reverse('app:course-detail', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = 'Parcours'
        verbose_name_plural = 'Parcours'


class VerbalProces(TimeStampModel):
    level = models.ForeignKey(
        Level, on_delete=models.CASCADE, verbose_name='Niveau')
    academic_year = models.CharField(
        max_length=20, verbose_name='Année académique', help_text='2015/2016')

    file = models.FileField(
        verbose_name='Fichier procès verbal', upload_to='proces/')

    student_list = models.FileField(
        verbose_name='Fichier étudiants',blank=True, null=True, upload_to='students/')

    def __str__(self):
        return '{} - {}'.format(self.level, self.academic_year)

    class Meta:
        verbose_name = 'Procès verbal'
        verbose_name_plural = 'Procès verbaux'


class Student(TimeStampModel):
    uid = models.UUIDField(blank=True, default=uuid.uuid4())
    first_name = models.CharField(
        max_length=200, blank=True, verbose_name='Prénom(s)')
    last_name = models.CharField(max_length=200, verbose_name='Nom(s)')
    serial_number = models.CharField(max_length=10, verbose_name='Matricule')
    date_of_birth = models.CharField(max_length=20, verbose_name='Date de naissance', help_text='Format: jj/mm/annee')
    place_of_birth = models.CharField(
        max_length=100, verbose_name='Lieu de naissance')
    region_of_origin = models.CharField(
        max_length=100, blank=True, verbose_name='Region d\'origine')
    father_name = models.CharField(
        max_length=255, verbose_name='Nom(s) du père')
    mother_name = models.CharField(
        max_length=255, verbose_name='Nom(s) de la mère')
    gender = models.CharField(max_length=10, verbose_name='Sexe', default='male', choices=(
        ('female', 'Feminin'), ('male', 'Masculin')))
    nationality = models.CharField(
        max_length=50,
        verbose_name='Nationnalité'
    )
    handicap = models.BooleanField(
        verbose_name='Êtes vous handicapé ?', default=False)
    refugee = models.BooleanField(
        verbose_name='Êtes vous un réfugié ?', default=False)

    course_of_study = models.ForeignKey(
        CourseOfStudy, on_delete=models.CASCADE, blank=True, null=True, related_name='students')

    verbal_proces = models.ManyToManyField(
        VerbalProces, blank=True, verbose_name='Procès verbal', related_name='students')

    objects = StudentManager()

    def get_full_name(self):
        return '{} {}'.format(self.last_name, self.first_name)

    def get_absolute_url(self):
        return reverse("app:student-detail", kwargs={"uid": self.uid})

    def __str__(self):
        return self.first_name + ' ' + self.last_name

    class Meta:
        verbose_name = 'Etudiant'
        verbose_name_plural = 'Etudiants'


class Speciality(CommonModel):
    course_of_study = models.ForeignKey(
        CourseOfStudy,
        on_delete=models.CASCADE,
        related_name='specialities'
    )

    class Meta:
        verbose_name = 'Spécialité'
        verbose_name_plural = 'Spécialités'


class BachelorAdmission(CommonModel):
    academic_year = models.CharField(
        max_length=10,
        blank=True,
        verbose_name='Année académique'
    )
    level = models.ForeignKey(
        Level,
        blank=True,
        on_delete=models.CASCADE,
        verbose_name='Niveau',
        related_name='bachelor_level')

    father_occupation = models.CharField(
        max_length=100,
        blank=True,
        verbose_name='Occupation du père')

    mother_occupation = models.CharField(
        max_length=100,
        blank=True,
        verbose_name='Occupation de la mère')

    parents_address = models.CharField(
        max_length=100,
        blank=True,
        verbose_name='Adresse des parents')

    course_of_study = models.ForeignKey(
        CourseOfStudy,
        blank=True,
        on_delete=models.CASCADE,
        verbose_name='Parcours de l\'étudiant',
        related_name='admissions_course')

    # Camerounian Bachelor Admission fields
    bac_serial = models.CharField(
        max_length=25,
        blank=True,
        verbose_name='Série Bac')

    grade = models.CharField(
        max_length=50,
        blank=True,
        verbose_name='Mention')

    date_obtained = models.DateField(
        blank=True,
        verbose_name='Année d\'obtention')

    # Foreign Bachelor Admission fields
    entry_qualification = models.CharField(
        max_length=100,
        blank=True,
        verbose_name='Diplôme d\'entrée')

    other_entry_qualification = models.CharField(
        max_length=100,
        verbose_name='Autre diplôme d\'entrée',
        blank=True
    )

    city = models.CharField(
        max_length=150,
        blank=True,
        verbose_name='Ville'
    )

    country = models.CharField(
        max_length=100,
        blank=True,
        verbose_name='Pays'
    )

    student = models.ForeignKey(
        Student,
        blank=True,
        on_delete=models.CASCADE,
        verbose_name='Etudiant'
    )

    def __str__(self):
        return '{} {}'.format(self.student.first_name, self.student.lastname)


class Folder(TimeStampModel):
    name = models.CharField(
        max_length=100,
        blank=True,
        verbose_name='Nom du dossier'
    )

    class Meta:
        verbose_name = 'Dossier étudiant'
        verbose_name_plural = 'Dossiers étudiant'


class Semester(TimeStampModel):
    number = models.IntegerField(
        verbose_name='Numero de semestre'
    )

    def __str__(self):
        return 'Semestre: {}'.format(self.number)

    class Meta:
        verbose_name = 'Semestre'
        verbose_name_plural = 'Semestres'


class DocumentType(TimeStampModel):
    name = models.CharField(max_length=255, verbose_name='Nom')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Type du document'
        verbose_name_plural = 'Types du document'


class Document(TimeStampModel):
    type = models.ForeignKey(
        DocumentType,
        on_delete=models.CASCADE,
        related_name='documents')
    # level = models.ForeignKey(
    #     Level,
    #     on_delete=models.CASCADE,
    #     verbose_name='niveau')
    semester = models.ForeignKey(
        Semester,
        on_delete=models.CASCADE,
        verbose_name='Semestre concerné'
    )
    student = models.ForeignKey(
        Student,
        on_delete=models.CASCADE,
        verbose_name='Etudiant',
        related_name='documents'
    )
    file = models.FileField(upload_to='documents/')
    file_name = models.CharField(
        max_length=150,
        verbose_name='Nom du fichier'
    )

    @property
    def name(self):
        return self.file_name

    def save(self):
        self.file_name = str(self.file).split('.')[0]
        super().save()

    class Meta:
        verbose_name = 'Document'
        verbose_name_plural = 'Documents'


class DocumentFile(TimeStampModel):
    file = models.FileField(upload_to='documents/', verbose_name='fichier')
    name = models.CharField(
        max_length=255,
        verbose_name='Nom du fichier'
    )
    ext = models.CharField(max_length=10, blank=True, verbose_name='extension')
    document = models.ForeignKey(
        Document,
        on_delete=models.CASCADE,
        related_name='files'
    )

    def __str__(self):
        return 'Fichier: {}'.format(self.pk)

    class Meta:
        verbose_name = 'Fichier du document'
        verbose_name_plural = 'Fichiers du document'

    # def save(self):
    #     strfile_splited = str(self.file).split('.')
    #     self.name = strfile_splited[0]
    #     self.ext = strfile_splited[1]
    #     super().save()

# class AcademicYear(TimeStampModel):
#     start_date = models.CharField()


class AdmissionFile(TimeStampModel):
    department = models.ForeignKey(
        Department,
        on_delete=models.CASCADE,
        verbose_name='Departement'
    )
    course_of_study = models.ForeignKey(
        CourseOfStudy,
        on_delete=models.CASCADE,
        verbose_name='Parcours',
        related_name='course_admissions'
    )
    level = models.ForeignKey(
        Level,
        on_delete=models.CASCADE,
        verbose_name='Niveau d\'étude'
    )
    # speciality = models.ForeignKey(
    #     Speciality,
    #     blank=True,
    #     on_delete=models.CASCADE,
    #     verbose_name='Spécialité',
    #     related_name='speciality_admissions'
    # )
    student = models.ForeignKey(
        Student,

app/templates/app/admission-form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block title %}
Formulaire enregistrement
{% endblock title %}

{% block breadcrumbs %}
  {{ block.super }}
  <li class="breadcrumb-item">
    <a href="{{student.get_absolute_url}}">{{student.get_full_name}}</a>
  </li>
  <li class="breadcrumb-item active">
    Nouvelle fiche d'inscription
  </li>
{% endblock breadcrumbs %}

{% block content %}
  <div class="row mt-4">
    <div class="col-lg-6">
      <!-- <h4>Etape: {{wizard.steps.step1}}</h4> -->
      <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <!-- {{ wizard.form.media }} -->
        
      {{form|crispy}}
        
        <!-- {{wizard.management_form}}
        {% if wizard.form.forms %}
        {{ wizard.form.management_form }}
        {% for form in wizard.form.forms %}
        {{ form }}
        {% endfor %}
        {% else %}
        {{ wizard.form }}
        {% endif %} -->
       
          <button class="btn btn-primary btn-sm ml-auto" type='submit'>Enregistrer l'étudiant</button>
      </form>

    </div>
</div>
{% endblock content %}

app/templates/app/course_study-detail.html
{% extends "base_site.html" %}

{% load static %}
{% load mathfilters %}

{% block title %}
{{title}}
{% endblock title %}

{% block breadcrumbs %}
{{ block.super }}
<li class="breadcrumb-item active">
  {{title}}
</li>
{% endblock breadcrumbs %}

{% block extrastyle %}
  <link rel="stylesheet" href="{% static 'css/datatables.min.css' %}">
{% endblock extrastyle %}

{% block content %}

<div class="row mt-4">
    <div class="col-12">
        <table id="table" class="table">
            <thead>
                <tr>
                    <th>Matricule</th>
                    <th>Nom(s) & Prenom(s)</th>
                    <th>Documents</th>
                </tr>
            </thead>
            <tbody>
                {% for student in students %}
                <tr>
                    <td><a href="{{student.get_absolute_url}}">{{student.serial_number}}</a></td>
                    <td>{{student.get_full_name}}</td>
                    <td>{{student.documents.count|add:student.admissions.count}}</td>
                </tr>
                {% endfor %}
                
            </tbody>
        </table>
    </div>
</div>


{% endblock content %}

{% block script %}
  <script src="{% static 'js/datatables.min.js' %}"></script>
{% endblock script %}

{% block javascript %}
$('#table').DataTable({
    'language': {
        "sEmptyTable":     "Aucune donnée disponible dans le tableau",
        "sInfo":           "Affichage de l'élément _START_ à _END_ sur _TOTAL_ éléments",
        "sInfoEmpty":      "Affichage de l'élément 0 à 0 sur 0 élément",
        "sInfoFiltered":   "(filtré à partir de _MAX_ éléments au total)",
        "sInfoPostFix":    "",
        "sInfoThousands":  ",",
        "sLengthMenu":     "Afficher _MENU_ éléments",
        "sLoadingRecords": "Chargement...",
        "sProcessing":     "Traitement...",
        "sSearch":         "Rechercher :",
        "sZeroRecords":    "Aucun élément correspondant trouvé",
        "oPaginate": {
            "sFirst":    "Premier",
            "sLast":     "Dernier",
            "sNext":     "Suivant",
            "sPrevious": "Précédent"
        },
        "oAria": {
            "sSortAscending":  ": activer pour trier la colonne par ordre croissant",
            "sSortDescending": ": activer pour trier la colonne par ordre décroissant"
        },
        "select": {
                "rows": {
                    "_": "%d lignes sélectionnées",
                    "0": "Aucune ligne sélectionnée",
                    "1": "1 ligne sélectionnée"
                } 
        }
    }
});
  
{% endblock javascript %}

app/templates/app/course_study-list.html
{% extends "base_site.html" %}

{% block title %}
  Parcours
{% endblock title %}


{% block content-body %}
  
{% endblock content-body %}

app/templates/app/document-form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block title %}
  Nouveau document
{% endblock title %}

{% block breadcrumbs %}
{{ block.super }}
  <li class="breadcrumb-item">
    <a href="{{student.get_absolute_url}}">{{student.get_full_name}}</a>
  </li>
  <li class="breadcrumb-item active">
    Nouveau document
  </li>
{% endblock breadcrumbs %}

{% block content %}
  <div class="row mt-4">
    <div class="col-7">

        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form|crispy}}
            <button class="btn btn-primary btn-sm">Ajouter le document</button>
        </form>

    </div>

  </div>
{% endblock content %}

app/templates/app/fail_serials.html
{% extends "base_site.html" %}

{% block title %}
  {{title}}
{% endblock title %}

{% block content %}
    
    <div class="row mt-5">
        <div class="col">
            
            <h4> Les matricules suivants n'ont pas été trouvés </h4>
            {% for serial in serials %}
              <p class="text-danger">{{serial}}</p>
            {% endfor %}
        </div>
    </div>

{% endblock content %}

app/templates/app/student-detail.html
{% extends "base.html" %}

{% load humanize %}
{% load sizify %}

{% block title %}
{{student.serial_number}}
{% endblock title %}

{% block breadcrumbs %}
{{ block.super }}
  <li class="breadcrumb-item active">
    {{student.get_full_name }}
  </li>
{% endblock breadcrumbs %}
{% block content %}

<div class="row mt-4 mb-3">
  <div class="col-12 d-flex align-items-center justify-content-between">
    <h5>
      
      {{student.serial_number}} - <span class="text-uppercase">{{student.get_full_name}}</span>
     
    </h5>
    <span class="float-right">
      <a href="{% url 'app:document-create' uid=student.uid %}" class="btn btn-secondary btn-sm">Nouveau document</a>
      <a href="{% url 'app:admission-form' uid=student.uid %}" class="btn btn-primary btn-sm">Ajouter une fiche d'inscription</a>
    </span>
  </div>
</div>
{% if messages %}
  {% for message in messages %}
    <div class="alert alert-{{message.tags}}">
      {{message}}
    </div>
  {% endfor %}
{% endif %}
<p class="mb-0 mt-5">Documents</p>
<hr class="mg-y-40 mt-0">
<div class="row">


  {% for document in student.documents.all %}
  <div class="col-sm-4 mb-4">
    {% include "app/includes/single-document.html" with item=document %}

  </div>
  {% empty %}
  <div class="col-12">
    <p class="text-center">Aucun document trouvé pour l'étudiant {{student.get_full_name}}</p>
  </div>
  {% endfor %}

</div>
<p class="mb-0 mt-5">Fiches d'inscription</p>

<hr class="mg-y-40 mt-0">
<div class="row">
{% for admission in student.admissions.all %}
<div class="col-sm-4">
  <div class="card card-file">
    <div class="dropdown-file">
      <a href="#" class="dropdown-link" data-toggle="dropdown"><i data-feather="more-vertical"></i></a>
      <div class="dropdown-menu dropdown-menu-right">
        <a href="#modalViewDetails" data-toggle="modal" class="dropdown-item details"><i data-feather="info"></i>
          Details</a>
  
        <a href="#" class="dropdown-item delete"><i data-feather="trash"></i>Supprimer</a>
      </div>
    </div><!-- dropdown -->
    <div class="card-file-thumb tx-danger">
      <i class="far fa-file"></i>
    </div>
    <div class="card-body">
      <h6><a href="{{admission.file.url}}" class="link-02" target="blank" >Fiche d'inscription: {{admission.level}}</a></h6>
    </div>
    <div class="card-footer"><span class="d-none d-sm-inline">Date d'ajout: </span><span class="text-dark">{{admission.created_at|naturalday}}</span></div>
  </div>
</div>
{% endfor %}
</div>
{% endblock content %}

app/templates/app/student-form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block title %}
  Ajouter un nouvel étudiant
{% endblock title %}

{% block breadcrumbs %}
{{ block.super }}
  <li class="breadcrumb-item active">
    nouvel étudiant
  </li>
{% endblock breadcrumbs %}

{% block content %}
  <div class="row mt-4">
    <div class="col-8">
      <form method="post">
  
          {% csrf_token %}
      
          <div class="form-row">
              <div class="form-group mb-0 col">
                {{form.serial_number|as_crispy_field}}
              </div>
            </div>
            <div class="form-row">
              <div class="form-group mb-0 col-md-6">
                {{form.last_name|as_crispy_field}}
              </div>
              <div class="form-group mb-0 col-md-6">
                {{form.first_name|as_crispy_field}}
              </div>
            </div>
            <div class="form-row">
              <div class="form-group mb-0 col-md-6">
                {{form.date_of_birth|as_crispy_field}}
              </div>
              <div class="form-group mb-0 col-md-6">
                {{form.place_of_birth|as_crispy_field}}
              </div>
            </div>
            <div class="form-row">
              
              <div class="form-group mb-0 col-md-6">
                {{form.gender|as_crispy_field}}
              </div>
            </div>
            <div class="form-row">
              <div class="form-group col col-md-6">
                <label for="">{{form.nationality.label}}*</label>
                <select name="nationality" id="nationality" class="form-control">
                  {% include "includes/countrydropdown.html" %}
                </select>
              </div>
              <div class="form-group col-md-6">
                <label for="id_region_of_origin">Région d'origine*</label>
                {% include "includes/regions.html" %}
              </div>
            </div>
            <div class="form-row">
              <div class="form-group mb-0 col-md-6">
                {{form.father_name|as_crispy_field}}
              </div>
              <div class="form-group mb-0 col-md-6">
                {{form.mother_name|as_crispy_field}}
              </div>
            </div>
            <div class="form-row">
              <div class="form-group mb-0 col-md-6">
                {{form.handicap|as_crispy_field}}
              </div>
              <div class="form-group mb-0 col-md-6">
                {{form.refugee|as_crispy_field}}
              </div>
            </div>
      
            <button class="btn btn-primary btn-sm">Enregister l'étudiant</button>
        </form>
    </div>
  </div>
{% endblock content %}

{% block javascript %}
  var country = "Cameroon"

  function process_selectedcountry(from) {
    var selectedCountry = $(from).children("option:selected").val();
    if(selectedCountry == country){
      $('#id_regions').removeAttr('disabled');
    }else{
      $('#id_regions').attr('disabled', 'disabled');
    }
  }

  process_selectedcountry('#nationality');

  <!-- $('#id_regions').attr('disabled', 'disabled'); -->
  $('#nationality').change(function(){
    process_selectedcountry(this);
  })

{% endblock javascript %}

app/templates/app/student-list.html
{% extends "base.html" %}

{% block title %}
  Recherche pour {{query}}
{% endblock title %}

{% block breadcrumbs %}
{{ block.super }}
  <li class="breadcrumb-item active">
    Recherche pour {{query}}
  </li>
{% endblock breadcrumbs %}

{% block content %}
<section class="py-4">
    <h4 class="mb-0">Résultats de récherches pour: <span class="text-primary">{{query}}</span></h4>
    <hr class="mg-b-40">
    <div class="row tx-14">
      {% for student in students %}
      <div class="col-sm-4 mb-4">
        {% include "app/includes/single-folder.html" with item=student %}
      </div>
  
      {% empty %}
      <div class="col-12">
        <h5 class="text-center text-primary">Aucun étudiant trouvé pour le matricule {{query}}</h5>
      </div>
      {% endfor %}
  
    </div>
  </section>
{% endblock content %}

app/templates/app/verbal_proces-form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block title %}
  Nouveau document
{% endblock title %}

{% block breadcrumbs %}
{{ block.super }}
  
  <li class="breadcrumb-item active">
    Nouveau procès verbal
  </li>
{% endblock breadcrumbs %}

{% block content %}
  <div class="row mt-4">
    <div class="col-7">

        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form|crispy}}
            <button class="btn btn-primary btn-sm">Ajouter le procès verbal</button>
        </form>

    </div>

  </div>
{% endblock content %}

app/templates/app/verbal_proces-list.html
{% extends "base_site.html" %}

{% block title %}
  {{title}}
{% endblock title %}

{% block breadcrumbs %}
{{ block.super }}
<li class="breadcrumb-item active">
    {{title}}
  </li>
{% endblock breadcrumbs %}

{% block content %}
  
    <div class="row mt-4">
        <div class="col">
            <table id="table" class="table">
                <thead>
                    <tr>
                        <th>Niveau</th>
                        <th>Année académique</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for proces in verbal_process %}
                    <tr>
                        <td>{{proces.level}}</td>
                        <td>{{proces.academic_year}}</td>
                        <td><a href="">Ajouter des étudiants</a></td>
                    </tr>
                    {% endfor %}
                    
                </tbody>
            </table>
        </div>
    </div>

{% endblock content %}

app/templates/app/verbal_process-preview.html
{% extends "base_site.html" %}

{% block title %}
  {{title}}
{% endblock title %}

{% block breadcrumbs %}
  {{ block.super }}
{% endblock breadcrumbs %}

{% block extrastyle %}
  <link rel="stylesheet" href="{% static 'css/datatables.min.css' %}">
{% endblock extrastyle %}


{% block content %}
  
    <div class="row mt-4">
        <div class="col">
            <table class="table">
                <thead>
                    <th>Matricule</th>
                    <th>Nom(s) et Prenom(s)</th>
                </thead>
                <tbody>
                    {% for student in students %}
                    <tr>
                        <td><a href="{{student.get_absolute_url}}">{{student.serial_number}}</a></td>
                        <td>{{student.get_full_name}}</td>
                    </tr>
                    {% endfor %}
                    
                </tbody>
            </table>
        </div>
    </div>

{% endblock content %}


{% block script %}
  <script src="{% static 'js/datatables.min.js' %}"></script>
{% endblock script %}

{% block javascript %}
$('#table').DataTable({
    'language': {
        "sEmptyTable":     "Aucune donnée disponible dans le tableau",
        "sInfo":           "Affichage de l'élément _START_ à _END_ sur _TOTAL_ éléments",
        "sInfoEmpty":      "Affichage de l'élément 0 à 0 sur 0 élément",
        "sInfoFiltered":   "(filtré à partir de _MAX_ éléments au total)",
        "sInfoPostFix":    "",
        "sInfoThousands":  ",",
        "sLengthMenu":     "Afficher _MENU_ éléments",
        "sLoadingRecords": "Chargement...",
        "sProcessing":     "Traitement...",
        "sSearch":         "Rechercher :",
        "sZeroRecords":    "Aucun élément correspondant trouvé",
        "oPaginate": {
            "sFirst":    "Premier",
            "sLast":     "Dernier",
            "sNext":     "Suivant",
            "sPrevious": "Précédent"
        },
        "oAria": {
            "sSortAscending":  ": activer pour trier la colonne par ordre croissant",
            "sSortDescending": ": activer pour trier la colonne par ordre décroissant"
        },
        "select": {
                "rows": {
                    "_": "%d lignes sélectionnées",
                    "0": "Aucune ligne sélectionnée",
                    "1": "1 ligne sélectionnée"
                } 
        }
    }
});
  
{% endblock javascript %}